//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class komentar
    {
        public int id { get; set; }
        public string tekst_komentara { get; set; }
        public System.DateTime datum { get; set; }
        public string id_korisnik { get; set; }
        public int id_post { get; set; }
    
        public virtual post post { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
