//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public post()
        {
            this.komentars = new HashSet<komentar>();
        }
    
        public int id { get; set; }
        public string naslov { get; set; }
        public string tekst_posta { get; set; }
        public System.DateTime datum { get; set; }
        public string id_korisnik { get; set; }
        public int id_kategorija { get; set; }
        public int id_slika { get; set; }
    
        public virtual kategorija kategorija { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<komentar> komentars { get; set; }
        public virtual slika slika { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
