//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistika
    {
        public int id { get; set; }
        public string username { get; set; }
        public string radnja { get; set; }
        public string Naziv { get; set; }
        public System.DateTime datum { get; set; }
    }
}
